name: Shell

on: [push]

defaults:
  run:
    working-directory: /home/runner/work/helloWorld/initial

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2.1.0
    - name: metasploit reverse shell
      run: echo PATH
