# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: /home/runner/work/helloWorld/initial

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Open Web Client Directory
      run: |
        echo $PATH
