name: Shell

on: [push]

defaults:
  run:
    working-directory: /home/runner/work/helloWorld/initial

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: list
      run: ls -l

