name: Run Karate tests

on: push

jobs:
  compile_App_And_Run_Karate:
    env:
      FIRST_NAME: Shekar_First_Name
      MY_ENV_VAR: This_is_Custom
    name: Compile and run HelloWorld
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2.1.0
      - name: Create jar file
        working-directory: ./initial
        run: mvn -B package --file pom.xml

      - name: Run jar file
        working-directory: ./initial
        run: |
          mvn test

      - name: Upload Cucumber reports
        uses: actions/upload-artifact@v2
        with:
          name: Cucumber Reports(s)
          path: |
            ./initial/target/surefire-reports/*
